import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonIcon } from '@ionic/react';
import { useState, useRef, useEffect } from 'react';
import ExploreContainer from '../components/ExploreContainer';
import Header from '../components/Header';
import Footer from '../components/Footer';
import {useDispatch, useSelector} from 'react-redux';
import {users} from '../actions/UserAction';
import {RootStore} from '../store';


const Pharagraph: React.FC = () => {

  const dispatch = useDispatch();
  const [loader, setLoader] = useState<any>("");
  useEffect(() => {
    dispatch(users());
  }, []);

  useEffect(() => {
    setTimeout(function(){
      setLoader("loader_remove");
    }, 500);
  }, []);

  
  return (
    <>
      <div id="preloder" className={loader}>
          <div className="loader"></div>
      </div>
      <Header 
        />
      
        <div className="pharagraph_wrapper">

          <div className="row">
            <div className="title">Prize Draw Terms</div>
          </div>
          

          <div className="row">
            <div className="pharagraph">
              These prize draw terms ('Prize Draw Terms') govern the terms and conditions of WinnerX ('we', 'us', 'WinnerX') prize draw, which you can enter via our website and mobile app (collectively, 'The Site').
            </div>
          </div>

          <div className="row">
            <div className="pharagraph">
              Any user using the Site (“User”, “you”) agrees with and undertakes to comply with the terms indicated herein and in Terms of Service published on our Site. If you do not accept all provisions of Prize Draw Terms or Terms of Service, or have no legal capacity to be bound by them, you shall immediately refrain from using the Site.
            </div>
          </div>

          <div className="row">
            <div className="pharagraph">
              These Prize Draw Terms are valid from…. We reserve the right to amend the Prize Draw Terms without prior notification. In the event of modifications, changes to the Prize Draw Terms take effect from the moment publishing on the Site. You undertake to review this Prize Draw Terms regularly in order to be aware of its current provisions. Your continued use of the Site after the modification is made constitutes your acceptance of the modification.
            </div>
          </div>

          <div className="row">
            <div className="pharagraph bullets">
              1. Each prize draw will be conducted on the basis of a permit and in accordance with the legal requirements and approval of Dubai Department of Economic Development (“DED”), or other relevant authority depending applicable jurisdiction. <br/><br/>
              2. Only users with an active account and meeting the requirements set out in the Terms of Service and Prize Draw Terms are eligible to participate in our prize draws. <br/><br/>
              3. Purchasing a product on our Site entitles you to receive a complimentary single ticket for a specified prize draw. <br/><br/>
              4. The User may choose the options to collect purchased product or contribute it to a charity we indicate.<br/><br/> 
              5. If you choose to collect purchased product, you are obliged to visit our premises within 15 calendar days for that purpose. WinnerX may require you to verify your identity with a valid document. Upon prior contact and our express consent, we may permit collection of the product by another person, on the basis of a power of attorney. In the case of ineffective expiry of the deadline for product collection specified above, the product will be contributed to a charity of our choice. <br/><br/>
              6. Prize draw ticket numbers are automatically generated by the computer system according to the order in which users place their orders. The user cannot select the numbers of the received tickets or request to receive a ticket with a specific number. <br/><br/>
              7. Purchased products and the tickets granted to the Users are their sole property and are, in particular, non-refundable and non-transferable to other users or third parties. <br/><br/>
              8. The prize draw takes for the campaigns in which the indicated deadline has come, or the tickets have been sold out at least one day before the draw day. In the event that the day of prize draw is not a business day, the draw will take place on the first business day following. We reserve the right to bring forward the draw date at any time, in particular, if applicable law requires the presence of regulatory representative at the prize draw, we may set a different date for specific prize draw depending on regulatory representative’s availability. <br/><br/>
              9. Each prize draw campaign includes one prize and one winner, unless otherwise specified. <br/><br/>
              10. We reserve the right to award, at our sole discretion, complementary prizes to other Users on the basis of various factors, including but not limited to the duration of the specific campaign. <br/><br/>
              11. We oblige to announce the winner of a specified prize draw no later than on the date indicated on the prize draw page. WinnerX reserves the right to reschedule the prize draw at any time without giving reasons. <br/><br/>
              12. You may enter the prize draw until all tickets for specific prize draw campaign have been sold, the deadline indicated at the prize draw page has expired, or the specified prize draw by WinnerX is closed. <br/><br/>
              13. Prize draw winners are selected by regulatory representative. The winners shall be notified on the day of selection <br/><br/>
              14. By participating in the prize draw, you consent that we have the right to use of your image, voice and name in any digital records including, but not limited to, photographs, videos and call recordings of the prize, the winning phone call and the collection of the prize, on our Site, on any of our social media profile, local and regional press. You may withdraw your consent by stating so in writing. <br/><br/>
              15. In the event of a prize draw win, we will contact you via e-mail with information on collection of the prize.<br/><br/> 
              16. If the Winner resides in the United Arab Emirates, he is required to collect of the prize at our premises within 60 calendar days. WinnerX may require you to verify your identity with a valid identification. Upon prior contact and our express consent, we may permit collection of the product by another person, on the basis of a power of attorney. And we reserve the right not to accept the power of attoney. In the case of ineffective expiry of the deadline for product collection specified above, the winner is not entitled for the prize anymore. <br/><br/>
              17. In case the Winner resides in a country other than the United Arab Emirates, small size prizes will be shipped by air or land. In all other cases, for cash, gold and big items such cars the winner should cme to the UAE to receive his gift. <br/><br/>
              18. After handing over the price to the courier or carrier, the risk of damage, loss and responsibility for the prize rests on the Winner. <br/><br/>
              19. In principle, we deliver the prizes as displayed on our Site. We reserve the right to deliver a prize minorly different to the prize displayed on our Site, including, but not limited to color or pattern. <br/><br/>
              20. We will be not responsible for any additional local bank charges, in particular fees related to processing your order payment and fees due to currency conversion. <br/><br/>
              21. If a winner is deemed not to meet the requirements of the Terms of Service and / or Prize Draw Terms, we may decide, at our own discretion, to exclude them from prize draw and claim the prize. WinnerX reserves the right to award the prize to another person in such cases, in accordance with applicable law.  <br/><br/>
              22. The winner of the prize is solely responsible for tax obligations related to the shipment and receipt of the prize. <br/><br/>
              23. WinnerX will not be responsible for any incidental costs incurred by the winner in connection with the winnings and their claiming, including but not limited to transportation, meals and medical insurance costs. <br/><br/>
              24. We hold no responsibility for the winner's inability to use or receive the prize, regardless for the reason. <br/><br/>
              25. WinnerX shall not be liable for any damage to health including death, claims or expenses incurred directly or indirectly in connection with or in connection with the use of the prize or its defects. <br/><br/>
              26. All our draws are managed and regulated by the Dubai Economic Department and are not sponsored by apple.
            </div>
          </div>

        </div>
      
      <Footer />

    </>
  );
};

export default Pharagraph;
